# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Demo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nDemo.proto\"\x1c\n\x0ctxRoadSensor\x12\x0c\n\x04\x66low\x18\x06 \x01(\r\"^\n\rtxRoadSensors\x12\x17\n\x0fstart_timestamp\x18\x01 \x01(\x04\x12\x15\n\rend_timestamp\x18\x02 \x01(\x04\x12\x1d\n\x06sensor\x18\x03 \x03(\x0b\x32\r.txRoadSensor\"\x89\x01\n\x13txRoadSensorsRecord\x12\x32\n\x07sensors\x18\x01 \x03(\x0b\x32!.txRoadSensorsRecord.SensorsEntry\x1a>\n\x0cSensorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.txRoadSensors:\x02\x38\x01\x62\x06proto3'
)




_TXROADSENSOR = _descriptor.Descriptor(
  name='txRoadSensor',
  full_name='txRoadSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flow', full_name='txRoadSensor.flow', index=0,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=42,
)


_TXROADSENSORS = _descriptor.Descriptor(
  name='txRoadSensors',
  full_name='txRoadSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='txRoadSensors.start_timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_timestamp', full_name='txRoadSensors.end_timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='txRoadSensors.sensor', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=138,
)


_TXROADSENSORSRECORD_SENSORSENTRY = _descriptor.Descriptor(
  name='SensorsEntry',
  full_name='txRoadSensorsRecord.SensorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='txRoadSensorsRecord.SensorsEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='txRoadSensorsRecord.SensorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=278,
)

_TXROADSENSORSRECORD = _descriptor.Descriptor(
  name='txRoadSensorsRecord',
  full_name='txRoadSensorsRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='txRoadSensorsRecord.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TXROADSENSORSRECORD_SENSORSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=278,
)

_TXROADSENSORS.fields_by_name['sensor'].message_type = _TXROADSENSOR
_TXROADSENSORSRECORD_SENSORSENTRY.fields_by_name['value'].message_type = _TXROADSENSORS
_TXROADSENSORSRECORD_SENSORSENTRY.containing_type = _TXROADSENSORSRECORD
_TXROADSENSORSRECORD.fields_by_name['sensors'].message_type = _TXROADSENSORSRECORD_SENSORSENTRY
DESCRIPTOR.message_types_by_name['txRoadSensor'] = _TXROADSENSOR
DESCRIPTOR.message_types_by_name['txRoadSensors'] = _TXROADSENSORS
DESCRIPTOR.message_types_by_name['txRoadSensorsRecord'] = _TXROADSENSORSRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

txRoadSensor = _reflection.GeneratedProtocolMessageType('txRoadSensor', (_message.Message,), {
  'DESCRIPTOR' : _TXROADSENSOR,
  '__module__' : 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:txRoadSensor)
  })
_sym_db.RegisterMessage(txRoadSensor)

txRoadSensors = _reflection.GeneratedProtocolMessageType('txRoadSensors', (_message.Message,), {
  'DESCRIPTOR' : _TXROADSENSORS,
  '__module__' : 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:txRoadSensors)
  })
_sym_db.RegisterMessage(txRoadSensors)

txRoadSensorsRecord = _reflection.GeneratedProtocolMessageType('txRoadSensorsRecord', (_message.Message,), {

  'SensorsEntry' : _reflection.GeneratedProtocolMessageType('SensorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _TXROADSENSORSRECORD_SENSORSENTRY,
    '__module__' : 'Demo_pb2'
    # @@protoc_insertion_point(class_scope:txRoadSensorsRecord.SensorsEntry)
    })
  ,
  'DESCRIPTOR' : _TXROADSENSORSRECORD,
  '__module__' : 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:txRoadSensorsRecord)
  })
_sym_db.RegisterMessage(txRoadSensorsRecord)
_sym_db.RegisterMessage(txRoadSensorsRecord.SensorsEntry)


_TXROADSENSORSRECORD_SENSORSENTRY._options = None
# @@protoc_insertion_point(module_scope)


